stages:
  - build
variables:
        IMAGE_NAME: k02a3041.p.ssafy.io:5000/test:latest

build:
  only:
    - master
    - developer
  stage: package
  services:
    - name: docker:stable-dind
  stage: build
  before_script:
    - mv -f /home/ubuntu/image /home/ubuntu/tmpImg
  script:
    - docker-compose build
    - docker-compose down
    - docker-compose up -d 
    - docker cp ./model s02p31a304_front_1:/usr/share/nginx/
  after_script:
    - mv -f /home/ubuntu/tmpImg /home/ubuntu/image
  tags:
    - test
    

