version: "3"
services:

    back-spring:
        build: back/back-spring/
        ports:
          - 8081:8081
        volumes:
          - /home/ubuntu/image:/uploads

    front:
        build: front/front-vue/
        ports:
          - 80:80
          - 443:443
        volumes:
          - /home/ubuntu/letsencrypt:/etc/letsencryt
          - /home/ubuntu/image:/usr/share/nginx/image

